// src/lib/mock-dashboard.ts
import type { WorkerDashboard } from "@/types/dashboard";

export const mockDashboard: WorkerDashboard = {
  verification_checklist: {
    progress: 67,
    all_verified: false,
    steps: [
      { name: "Phone Verification", status: "completed" },
      { name: "Identity Document", status: "completed" },
      { name: "Skill Assessment", status: "in_review", eta: "24h" },
      { name: "Portfolio Moderation", status: "in_review", eta: "48h" },
      { name: "Agent Physical Verification", status: "pending" },
      { name: "Profile Completion", status: "completed" },
    ],
  },
  trust_score: 82.5,
  trust_score_breakdown: [
    { component: "Assessment Scores", weight: 25, score: 88, description: "Average of top 3 assessment scores" },
    { component: "Completion Rate", weight: 20, score: 95, description: "Completed / (Completed + Cancelled)" },
    { component: "On-Time Rate", weight: 15, score: 90, description: "Delivered on or before deadline" },
    { component: "Dispute Rate", weight: 15, score: 8, description: "Lower is better. You have 0 disputes." },
    { component: "Repeat-Hire Rate", weight: 15, score: 70, description: "Employers who hired you 2+ times" },
    { component: "Peer Vouches", weight: 10, score: 45, description: "Verified vouches from other workers" },
  ],
  matched_opportunities: [
    {
      id: "j001",
      title: "React Frontend Developer for Mobile Banking Dashboard",
      employer_name: "FinTech Ghana Ltd",
      employer_rating: 4.5,
      budget_ghs: 3000,
      budget_type: "fixed",
      skills_required: ["React Developer", "TypeScript", "UI Designer"],
      skills_matched: ["React Developer", "TypeScript"],
      posted_at: "2026-02-15T10:00:00Z",
      match_percentage: 92,
    },
    {
      id: "j003",
      title: "UI/UX Designer for SaaS Platform Redesign",
      employer_name: "TechHub Accra",
      employer_rating: 4.8,
      budget_ghs: 5000,
      budget_type: "fixed",
      skills_required: ["UI Designer", "Figma"],
      skills_matched: ["UI Designer"],
      posted_at: "2026-02-13T14:00:00Z",
      match_percentage: 85,
    },
    {
      id: "j006",
      title: "Copywriter for Mobile App Launch Campaign",
      employer_name: "FinTech Ghana Ltd",
      employer_rating: 4.5,
      budget_ghs: 1500,
      budget_type: "fixed",
      skills_required: ["Copywriting", "Content Strategy"],
      skills_matched: [],
      posted_at: "2026-02-11T09:00:00Z",
      match_percentage: 60,
    },
  ],
  active_jobs: [
    {
      id: "aj001",
      title: "Landing Page Redesign",
      employer_name: "EcoShop Ghana",
      status: "in_progress",
      budget_ghs: 1200,
      milestone_progress: 50,
      next_milestone: "Mobile responsive review",
      started_at: "2026-02-10T08:00:00Z",
    },
    {
      id: "aj002",
      title: "API Integration for Payment Gateway",
      employer_name: "PayHub Accra",
      status: "awaiting_review",
      budget_ghs: 2500,
      milestone_progress: 100,
      next_milestone: "Client approval",
      started_at: "2026-02-01T09:00:00Z",
    },
  ],
  earnings: {
    this_week: 450,
    this_month: 1800,
    all_time: 12500,
    platform_average: 3200,
    currency: "GHS",
  },
};
