// src/lib/mock-employer.ts
import type { EmployerDashboard, EmployerPaymentsData } from "@/types/employer";

export const mockEmployerDashboard: EmployerDashboard = {
  stats: {
    total_jobs_posted: 12,
    total_hired: 8,
    total_spent_ghs: 15000,
    average_rating: 4.5,
  },
  active_jobs: [
    {
      id: "j001",
      title: "React Frontend Developer for Mobile Banking Dashboard",
      status: "open",
      applications_count: 8,
      hired_count: 0,
      budget_ghs: 3000,
      posted_at: "2026-02-15T10:00:00Z",
    },
    {
      id: "j006",
      title: "Copywriter for Mobile App Launch Campaign",
      status: "open",
      applications_count: 12,
      hired_count: 0,
      budget_ghs: 1500,
      posted_at: "2026-02-11T09:00:00Z",
    },
    {
      id: "aj001",
      title: "Landing Page Redesign",
      status: "in_progress",
      applications_count: 5,
      hired_count: 1,
      budget_ghs: 1200,
      posted_at: "2026-02-10T08:00:00Z",
    },
  ],
  pending_applications: [
    {
      id: "app001",
      job_id: "j001",
      job_title: "React Frontend Developer",
      worker_id: "w001",
      worker_name: "Akua Serwaa",
      worker_trust_score: 82.5,
      cover_note: "I have 3 years of React experience building fintech dashboards. My portfolio includes similar mobile banking projects.",
      applied_at: "2026-02-16T08:00:00Z",
    },
    {
      id: "app002",
      job_id: "j001",
      job_title: "React Frontend Developer",
      worker_id: "w003",
      worker_name: "Ama Nyarko",
      worker_trust_score: 55.0,
      cover_note: "I am a fast learner with React and TypeScript. I have completed 7 projects on the platform with 5-star reviews.",
      applied_at: "2026-02-16T09:30:00Z",
    },
    {
      id: "app003",
      job_id: "j006",
      job_title: "Copywriter for Mobile App Launch",
      worker_id: "w003",
      worker_name: "Ama Nyarko",
      worker_trust_score: 55.0,
      cover_note: "I specialize in brand copywriting for Ghanaian audiences. I write in both English and Twi.",
      applied_at: "2026-02-15T14:00:00Z",
    },
  ],
  quick_rehire: [
    {
      id: "w001",
      user_id: "u001",
      full_name: "Akua Serwaa",
      category: "digital",
      bio: "",
      location_district: "Accra Metropolitan",
      hourly_rate_ghs: 75.0,
      trust_score: 82.5,
      is_visible_in_search: true,
      verification_level: "verified",
      global_earner_status: false,
      badge: "Top Rated",
      completed_jobs: 34,
      skills: [
        { id: "s1", name: "React Developer", assessment_score: 88, verified: true, assessment_required: true },
      ],
      portfolio: [],
      reviews: [],
    },
  ],
};

export const mockEmployerPayments: EmployerPaymentsData = {
  total_in_escrow_ghs: 4700,
  active_escrows: [
    {
      id: "esc001",
      job_id: "aj001",
      job_title: "Landing Page Redesign",
      worker_name: "Akua Serwaa",
      amount_ghs: 1200,
      status: "held",
      funded_at: "2026-02-10T08:30:00Z",
      release_eligible_at: "2026-02-20T08:30:00Z",
    },
    {
      id: "esc002",
      job_id: "aj002",
      job_title: "API Integration for Payment Gateway",
      worker_name: "Akua Serwaa",
      amount_ghs: 2500,
      status: "held",
      funded_at: "2026-02-01T09:00:00Z",
      release_eligible_at: "2026-02-18T09:00:00Z",
    },
    {
      id: "esc003",
      job_id: "j003",
      job_title: "UI/UX Designer for SaaS Platform",
      worker_name: "David Addo",
      amount_ghs: 1000,
      status: "released",
      funded_at: "2026-01-15T10:00:00Z",
    },
  ],
  completed_payments: [
    {
      id: "esc004",
      job_id: "j004",
      job_title: "UI Design Consultation",
      worker_name: "Akua Serwaa",
      amount_ghs: 300,
      status: "released",
      funded_at: "2026-02-05T11:00:00Z",
    },
  ],
};
