// src/lib/mock-academy.ts
import type { Course, Instructor } from "@/types/academy";

const instructors: Instructor[] = [
  {
    id: "instructor-001",
    name: "Kofi Mensah",
    avatar_url: "/assets/images/avatars/kofi.jpg",
    bio: "Full Stack Developer with 8 years experience building web applications for African startups",
    rating: 4.9,
    courses_count: 5,
    students_count: 2341,
  },
  {
    id: "instructor-002",
    name: "Ama Asante",
    avatar_url: "/assets/images/avatars/ama.jpg",
    bio: "Digital Marketer specializing in social media growth for African SMEs",
    rating: 4.8,
    courses_count: 3,
    students_count: 1876,
  },
  {
    id: "instructor-003",
    name: "Kwame Appiah",
    avatar_url: "/assets/images/avatars/kwame.jpg",
    bio: "Graphic Designer & Brand Strategist with 10 years experience",
    rating: 4.9,
    courses_count: 4,
    students_count: 3210,
  },
  {
    id: "instructor-004",
    name: "Akua Boatemaa",
    avatar_url: "/assets/images/avatars/akua.jpg",
    bio: "Freelance Writer & Content Creator with a focus on African storytelling",
    rating: 4.7,
    courses_count: 2,
    students_count: 987,
  },
  {
    id: "instructor-005",
    name: "Yaw Boakye",
    avatar_url: "/assets/images/avatars/yaw.jpg",
    bio: "Data Analyst & Excel Expert with 7 years experience in the finance industry",
    rating: 4.8,
    courses_count: 3,
    students_count: 1654,
  },
];

export const mockCourses: Course[] = [
  {
    id: "course-001",
    title: "Web Development Fundamentals for Beginners",
    short_description: "Learn HTML, CSS & JavaScript to build your first website from scratch",
    description: "This comprehensive course is designed specifically for complete beginners in Africa looking to start their journey in tech. You'll learn core web development skills through hands-on projects that are relevant to the African context.",
    price_ghs: 50,
    thumbnail_url: "/assets/images/academy/web-dev.jpg",
    category: "Technology",
    level: "beginner",
    duration_hours: 12,
    lessons_count: 24,
    instructor: instructors[0],
    rating: 4.9,
    reviews_count: 324,
    is_featured: true,
    tags: ["HTML", "CSS", "JavaScript", "Web Development"],
    requirements: ["A computer with internet access", "Basic computer literacy"],
    what_youll_learn: [
      "Build modern, responsive websites",
      "Understand HTML, CSS, and JavaScript fundamentals",
      "Create projects you can add to your portfolio",
      "Prepare for junior web developer roles",
    ],
    curriculum: [
      {
        id: "lesson-001-01",
        course_id: "course-001",
        title: "Introduction to Web Development",
        description: "Learn what web development is and how the web works",
        duration_seconds: 1200,
        order: 1,
        is_free_preview: true,
      },
      {
        id: "lesson-001-02",
        course_id: "course-001",
        title: "HTML Basics",
        description: "Learn the building blocks of web pages",
        duration_seconds: 1800,
        order: 2,
      },
      {
        id: "lesson-001-03",
        course_id: "course-001",
        title: "CSS Fundamentals",
        description: "Style your web pages with CSS",
        duration_seconds: 2400,
        order: 3,
      },
    ],
  },
  {
    id: "course-002",
    title: "Social Media Marketing for African SMEs",
    short_description: "Grow your business's online presence using Facebook, Instagram, TikTok & X",
    description: "Learn proven strategies to market your small or medium business online across African markets. This course covers platforms popular in Africa.",
    price_ghs: 60,
    thumbnail_url: "/assets/images/academy/social-media.jpg",
    category: "Business",
    level: "beginner",
    duration_hours: 10,
    lessons_count: 20,
    instructor: instructors[1],
    rating: 4.8,
    reviews_count: 256,
    is_featured: true,
    tags: ["Marketing", "Social Media", "Facebook", "Instagram", "TikTok"],
    requirements: ["A social media account", "A business or product to market"],
    what_youll_learn: [
      "Create engaging content for African audiences",
      "Grow your follower base organically",
      "Run cost-effective ads targeting African users",
      "Measure your results and optimize",
    ],
    curriculum: [
      {
        id: "lesson-002-01",
        course_id: "course-002",
        title: "Understanding Social Media in Africa",
        description: "Overview of popular platforms and user behavior in African markets",
        duration_seconds: 900,
        order: 1,
        is_free_preview: true,
      },
    ],
  },
  {
    id: "course-003",
    title: "Graphic Design Masterclass with Canva",
    short_description: "Design professional flyers, logos, and social media posts without prior experience",
    description: "Learn to create stunning designs using Canva, a free design tool perfect for entrepreneurs and freelancers in Africa.",
    price_ghs: 70,
    thumbnail_url: "/assets/images/academy/graphic-design.jpg",
    category: "Design",
    level: "beginner",
    duration_hours: 8,
    lessons_count: 16,
    instructor: instructors[2],
    rating: 4.9,
    reviews_count: 412,
    is_featured: true,
    tags: ["Canva", "Graphic Design", "Logo Design", "Visual Branding"],
    requirements: ["A computer or smartphone with internet access"],
    what_youll_learn: [
      "Design professional graphics without expensive software",
      "Create a brand identity for your business",
      "Design social media posts that stand out",
      "Offer design services as a freelancer",
    ],
    curriculum: [
      {
        id: "lesson-003-01",
        course_id: "course-003",
        title: "Introduction to Canva",
        description: "Get familiar with Canva's interface and tools",
        duration_seconds: 1080,
        order: 1,
        is_free_preview: true,
      },
    ],
  },
  {
    id: "course-004",
    title: "Freelance Writing Essentials",
    short_description: "Start your writing career and land clients as a content writer",
    description: "Learn how to write compelling content for clients, build your portfolio, and find freelance writing opportunities.",
    price_ghs: 45,
    thumbnail_url: "/assets/images/academy/freelance-writing.jpg",
    category: "Writing",
    level: "beginner",
    duration_hours: 9,
    lessons_count: 18,
    instructor: instructors[3],
    rating: 4.7,
    reviews_count: 189,
    is_featured: false,
    tags: ["Writing", "Freelancing", "Content Creation", "Copywriting"],
    requirements: ["Good command of English", "A passion for writing"],
    what_youll_learn: [
      "Write engaging blog posts and articles",
      "Create a professional writing portfolio",
      "Find and pitch clients",
      "Price your writing services appropriately",
    ],
    curriculum: [
      {
        id: "lesson-004-01",
        course_id: "course-004",
        title: "Introduction to Freelance Writing",
        description: "What it means to be a freelance writer in Africa today",
        duration_seconds: 1020,
        order: 1,
        is_free_preview: true,
      },
    ],
  },
  {
    id: "course-005",
    title: "Excel for Small Business Owners",
    short_description: "Master Excel to manage finances, inventory, and reports for your business",
    description: "Learn practical Excel skills that every African small business owner should know.",
    price_ghs: 55,
    thumbnail_url: "/assets/images/academy/excel.jpg",
    category: "Business",
    level: "beginner",
    duration_hours: 11,
    lessons_count: 22,
    instructor: instructors[4],
    rating: 4.8,
    reviews_count: 287,
    is_featured: false,
    tags: ["Excel", "Finance", "Business", "Data Analysis"],
    requirements: ["Microsoft Excel or Google Sheets", "Basic computer skills"],
    what_youll_learn: [
      "Organize your business data in Excel",
      "Create financial statements and reports",
      "Use formulas and functions to save time",
      "Visualize data with charts and graphs",
    ],
    curriculum: [
      {
        id: "lesson-005-01",
        course_id: "course-005",
        title: "Excel Fundamentals for Business",
        description: "Getting started with Excel and basic operations",
        duration_seconds: 1140,
        order: 1,
        is_free_preview: true,
      },
    ],
  },
];
