// src/lib/mock-phase2.ts
import type {
  CountryConfig,
  BookingBundle,
  BundleBooking,
  OnlineListing,
  OnlineListingApplication,
  Course,
  Lesson,
  Enrolment,
  LocaleConfig,
  WorkerMatch,
  EmployerAnalytics,
  IncomeCertificateMetadata,
} from "@/types/phase2";

// ── Country Configs ──────────────────────

export const mockCountries: CountryConfig[] = [
  {
    code: "ghana",
    name: "Ghana",
    flag: "🇬🇭",
    currency: "GHS",
    currencySymbol: "GH₵",
    paymentProviders: ["mtn_momo", "airteltigo_momo", "vodafone_cash", "wise", "stripe"],
    idVerificationTypes: ["Ghana Card", "Passport", "Driver's License"],
    districts: [
      "Accra Metropolitan",
      "Adenta Municipal",
      "Ashaiman Municipal",
      "Kumasi Metropolitan",
      "Tamale Metropolitan",
      "Tema Metropolitan",
      "Cape Coast Metropolitan",
      "Sekondi-Takoradi Metropolitan",
    ],
  },
  {
    code: "nigeria",
    name: "Nigeria",
    flag: "🇳🇬",
    currency: "NGN",
    currencySymbol: "₦",
    paymentProviders: ["opay", "wise", "stripe"],
    idVerificationTypes: ["NIN", "BVN", "PVC", "International Passport"],
    districts: [
      "Lagos Island",
      "Lagos Mainland",
      "Abuja Municipal",
      "Kano Municipal",
      "Port Harcourt",
      "Ibadan South",
      "Enugu North",
      "Benin City",
    ],
  },
  {
    code: "kenya",
    name: "Kenya",
    flag: "🇰🇪",
    currency: "KES",
    currencySymbol: "KSh",
    paymentProviders: ["mpesa", "wise", "stripe"],
    idVerificationTypes: ["National ID", "Passport", "Military ID"],
    districts: [
      "Nairobi County",
      "Mombasa County",
      "Kisumu County",
      "Kiambu County",
      "Nakuru County",
      "Eldoret",
      "Kakamega",
      "Thika",
    ],
  },
];

// ── Locale Configs ──────────────────────

export const mockLocales: LocaleConfig[] = [
  {
    code: "en",
    name: "English",
    nativeName: "English",
    flag: "🇬🇧",
    isRTL: false,
  },
  {
    code: "fr",
    name: "French",
    nativeName: "Français",
    flag: "🇫🇷",
    isRTL: false,
  },
  {
    code: "twi",
    name: "Twi",
    nativeName: "Twi",
    flag: "🇬🇭",
    isRTL: false,
  },
  {
    code: "ha",
    name: "Hausa",
    nativeName: "Hausa",
    flag: "🇳🇬",
    isRTL: false,
  },
];

// ── Booking Bundles (Educators) ──────────────────────

export const mockBookingBundles: BookingBundle[] = [
  {
    id: "bb001",
    worker_id: "w007",
    title: "BECE Math Prep Bundle (10 sessions)",
    description: "Comprehensive 10-session package covering all BECE mathematics topics with practice exams",
    session_count: 10,
    session_duration_minutes: 60,
    total_price_ghs: 800,
    discounted_price_ghs: 700,
    subject: "Mathematics",
    level: "JHS",
    is_active: true,
    created_at: "2026-02-01T10:00:00Z",
  },
  {
    id: "bb002",
    worker_id: "w008",
    title: "Essay Writing Intensive (5 sessions)",
    description: "Master essay writing for SHS exams — 5 sessions focused on structure, grammar, and style",
    session_count: 5,
    session_duration_minutes: 45,
    total_price_ghs: 350,
    subject: "English Language",
    level: "SHS",
    is_active: true,
    created_at: "2026-02-05T09:00:00Z",
  },
  {
    id: "bb003",
    worker_id: "w007",
    title: "WASSCE Math Crash Course (8 sessions)",
    description: "Intensive 8-session WASSCE preparation covering Core Maths and Elective Maths",
    session_count: 8,
    session_duration_minutes: 90,
    total_price_ghs: 960,
    discounted_price_ghs: 850,
    subject: "Further Mathematics",
    level: "SHS",
    is_active: true,
    created_at: "2026-02-10T12:00:00Z",
  },
];

export const mockBundleBookings: BundleBooking[] = [
  {
    id: "bkb001",
    bundle_id: "bb001",
    worker_id: "w007",
    client_id: "e008",
    client_name: "Amoah Family",
    sessions_scheduled: [
      "2026-03-01T16:00:00Z",
      "2026-03-03T16:00:00Z",
      "2026-03-05T16:00:00Z",
      "2026-03-08T16:00:00Z",
      "2026-03-10T16:00:00Z",
    ],
    sessions_completed: 2,
    total_sessions: 10,
    status: "in_progress",
    paid_amount_ghs: 700,
    payment_status: "paid",
    created_at: "2026-02-20T08:00:00Z",
  },
];

// ── Online Income Listings ──────────────────────

export const mockOnlineListings: OnlineListing[] = [
  {
    id: "ol001",
    title: "Customer Records Data Entry (500 records)",
    description: "Enter customer contact information from scanned forms into Excel template",
    task_type: "data_entry",
    payout_currency: "GHS",
    payout_per_task: 0.5,
    total_available: 500,
    total_remaining: 320,
    estimated_time_minutes_per_task: 1,
    requirements: ["Excel proficiency", "99% accuracy required", "Available within 3 days"],
    is_active: true,
    is_curated: true,
    verified_worker_only: true,
    created_at: "2026-02-18T08:00:00Z",
    expires_at: "2026-02-25T08:00:00Z",
  },
  {
    id: "ol002",
    title: "Market Research Transcription (10 hours)",
    description: "Transcribe 10 hours of consumer interview audio from English Twi mix",
    task_type: "transcription",
    payout_currency: "USD",
    payout_per_task: 0.5,
    total_available: 600,
    total_remaining: 480,
    estimated_time_minutes_per_task: 1.5,
    requirements: ["Typing speed 60 WPM+", "Able to understand Twi", "Fluent English"],
    is_active: true,
    is_curated: true,
    verified_worker_only: true,
    created_at: "2026-02-17T14:00:00Z",
  },
  {
    id: "ol003",
    title: "Image Tagging Micro-Tasks (1000 tasks)",
    description: "Classify product images into 20 predefined categories",
    task_type: "micro_task",
    payout_currency: "GHS",
    payout_per_task: 0.15,
    total_available: 1000,
    total_remaining: 1000,
    estimated_time_minutes_per_task: 0.25,
    requirements: ["Internet access", "Attention to detail"],
    is_active: true,
    is_curated: true,
    verified_worker_only: false,
    created_at: "2026-02-19T11:00:00Z",
  },
  {
    id: "ol004",
    title: "Consumer Surveys (100 surveys)",
    description: "Complete 15-minute consumer surveys for a local FMCG brand",
    task_type: "survey",
    payout_currency: "GHS",
    payout_per_task: 2.5,
    total_available: 100,
    total_remaining: 87,
    estimated_time_minutes_per_task: 15,
    requirements: ["Lagos residents only", "Smartphone required", "18+"],
    is_active: true,
    is_curated: true,
    verified_worker_only: false,
    created_at: "2026-02-16T13:00:00Z",
  },
];

export const mockOnlineApplications: OnlineListingApplication[] = [
  {
    id: "ola001",
    listing_id: "ol001",
    worker_id: "w009",
    status: "in_progress",
    tasks_completed: 180,
    total_earned: 90,
    applied_at: "2026-02-18T09:00:00Z",
    approved_at: "2026-02-18T10:00:00Z",
  },
  {
    id: "ola002",
    listing_id: "ol002",
    worker_id: "w009",
    status: "approved",
    tasks_completed: 120,
    total_earned: 60,
    applied_at: "2026-02-17T15:00:00Z",
    approved_at: "2026-02-17T16:30:00Z",
  },
];

// ── AfriSkills Academy Courses ──────────────────────

export const mockCourses: Course[] = [
  {
    id: "c001",
    instructor_id: "w007",
    instructor_name: "Nana Kofi Mensah",
    title: "BECE Mathematics Mastery",
    description: "Complete BECE mathematics preparation with video lessons, practice questions, and mock exams",
    category: "Mathematics",
    level: "beginner",
    price_ghs: 150,
    revenue_share_percent: 70,
    total_lessons: 24,
    total_duration_minutes: 720,
    rating: 4.8,
    students_enrolled: 342,
    is_published: true,
    created_at: "2026-01-15T10:00:00Z",
    updated_at: "2026-02-10T10:00:00Z",
  },
  {
    id: "c002",
    instructor_id: "w008",
    instructor_name: "Efua Asantewaa",
    title: "English Essay Writing Fundamentals",
    description: "Learn how to write compelling essays, letters, and reports for school and work",
    category: "English Language",
    level: "beginner",
    price_ghs: 100,
    revenue_share_percent: 70,
    total_lessons: 18,
    total_duration_minutes: 450,
    rating: 4.6,
    students_enrolled: 215,
    is_published: true,
    created_at: "2026-01-20T09:00:00Z",
    updated_at: "2026-02-12T09:00:00Z",
  },
  {
    id: "c003",
    instructor_id: "w001",
    instructor_name: "Akua Serwaa",
    title: "Introduction to Web Development (HTML/CSS)",
    description: "Build your first website from scratch with HTML and CSS — no coding experience required!",
    category: "Digital Skills",
    level: "beginner",
    price_ghs: 200,
    revenue_share_percent: 70,
    total_lessons: 30,
    total_duration_minutes: 900,
    rating: 4.9,
    students_enrolled: 520,
    is_published: true,
    created_at: "2026-02-01T12:00:00Z",
    updated_at: "2026-02-15T12:00:00Z",
  },
  {
    id: "c004",
    instructor_id: "w004",
    instructor_name: "Yaw Takyi",
    title: "Basic Plumbing for Beginners",
    description: "Learn essential plumbing skills for home repairs and start earning as a handyman",
    category: "Trade Skills",
    level: "beginner",
    price_ghs: 120,
    revenue_share_percent: 70,
    total_lessons: 15,
    total_duration_minutes: 360,
    rating: 4.5,
    students_enrolled: 98,
    is_published: true,
    created_at: "2026-02-05T08:00:00Z",
    updated_at: "2026-02-16T08:00:00Z",
  },
  {
    id: "c005",
    instructor_id: "w003",
    instructor_name: "Ama Nyarko",
    title: "Copywriting for Small Businesses",
    description: "Write sales copy that converts: product descriptions, ads, emails, and social media posts",
    category: "Digital Skills",
    level: "intermediate",
    price_ghs: 180,
    revenue_share_percent: 70,
    total_lessons: 22,
    total_duration_minutes: 580,
    rating: 4.7,
    students_enrolled: 176,
    is_published: true,
    created_at: "2026-02-10T11:00:00Z",
    updated_at: "2026-02-17T11:00:00Z",
  },
];

export const mockLessons: Record<string, Lesson[]> = {
  c001: [
    {
      id: "l001",
      course_id: "c001",
      title: "Introduction to BECE Math & Study Tips",
      description: "Welcome and study plan for the course",
      video_url: "https://cdn.cloudflare.r2.example.com/lessons/c001/l001.mp4",
      duration_minutes: 15,
      order_index: 1,
      free_preview: true,
      created_at: "2026-01-15T10:00:00Z",
    },
    {
      id: "l002",
      course_id: "c001",
      title: "Number Bases & Operations",
      video_url: "https://cdn.cloudflare.r2.example.com/lessons/c001/l002.mp4",
      duration_minutes: 30,
      order_index: 2,
      free_preview: true,
      created_at: "2026-01-15T10:00:00Z",
    },
    {
      id: "l003",
      course_id: "c001",
      title: "Fractions, Decimals & Percentages",
      video_url: "https://cdn.cloudflare.r2.example.com/lessons/c001/l003.mp4",
      duration_minutes: 35,
      order_index: 3,
      free_preview: false,
      created_at: "2026-01-15T10:00:00Z",
    },
  ],
  c003: [
    {
      id: "l100",
      course_id: "c003",
      title: "Welcome & What You'll Build",
      video_url: "https://cdn.cloudflare.r2.example.com/lessons/c003/l100.mp4",
      duration_minutes: 10,
      order_index: 1,
      free_preview: true,
      created_at: "2026-02-01T12:00:00Z",
    },
  ],
};

export const mockEnrolments: Enrolment[] = [
  {
    id: "en001",
    course_id: "c003",
    student_id: "u005",
    student_name: "Kojo Essel",
    status: "in_progress",
    progress_percent: 30,
    completed_lessons: ["l100"],
    enrolled_at: "2026-02-05T10:00:00Z",
  },
  {
    id: "en002",
    course_id: "c001",
    student_id: "u006",
    student_name: "Fatima Ibrahim",
    status: "completed",
    progress_percent: 100,
    completed_lessons: ["l001", "l002", "l003"],
    assessment_score: 88,
    certificate_url: "https://cdn.cloudflare.r2.example.com/certificates/en002.pdf",
    enrolled_at: "2026-01-20T10:00:00Z",
    completed_at: "2026-02-10T10:00:00Z",
  },
];

// ── Auto-Matching ──────────────────────

export const mockWorkerMatches: WorkerMatch[] = [
  {
    id: "wm001",
    job_id: "j001",
    worker_id: "w001",
    match_score: 92,
    skill_match_percent: 95,
    trust_score_percent: 88,
    rate_match_percent: 90,
    location_match_percent: 90,
    reasons: [
      "All 3 required skills verified",
      "Trust Score 82.5 — above employer's threshold",
      "Hourly rate GHS 75 within budget range",
      "Based in Accra Metropolitan — matches job location",
    ],
    created_at: "2026-02-15T11:00:00Z",
    is_viewed: false,
  },
  {
    id: "wm002",
    job_id: "j009",
    worker_id: "w007",
    match_score: 98,
    skill_match_percent: 100,
    trust_score_percent: 96,
    rate_match_percent: 100,
    location_match_percent: 95,
    reasons: [
      "Verified Mathematics Tutor with BECE Prep specialty",
      "Trust Score 95.0 — Verified Expert badge",
      "Session price GHS 80 matches exactly",
      "Located in Accra Metropolitan — same district",
    ],
    created_at: "2026-02-17T10:00:00Z",
    is_viewed: true,
  },
  {
    id: "wm003",
    job_id: "j011",
    worker_id: "w009",
    match_score: 94,
    skill_match_percent: 100,
    trust_score_percent: 92,
    rate_match_percent: 90,
    location_match_percent: 90,
    reasons: [
      "Verified Data Entry & Transcription specialist",
      "Trust Score 92.0 — Top Rated badge",
      "Global earner — eligible for USD payouts",
      "40 hours/week available",
    ],
    created_at: "2026-02-18T09:00:00Z",
    is_viewed: false,
  },
  {
    id: "wm004",
    job_id: "j004",
    worker_id: "w004",
    match_score: 89,
    skill_match_percent: 90,
    trust_score_percent: 96,
    rate_match_percent: 85,
    location_match_percent: 80,
    reasons: [
      "Verified Expert plumber with 58 completed jobs",
      "Trust Score 91.0 — highest in category",
      "Emergency 2-hour response available",
      "Serves Adenta area — close to Kumasi",
    ],
    created_at: "2026-02-16T08:00:00Z",
    is_viewed: true,
  },
];

// ── Employer Analytics ──────────────────────

export const mockEmployerAnalytics: EmployerAnalytics = {
  employer_id: "e001",
  time_to_hire_days: {
    average: 2.4,
    by_month: {
      "2026-01": 2.8,
      "2026-02": 2.1,
    },
  },
  worker_scores: {
    average: 86.5,
    distribution: {
      70: 2,
      80: 8,
      90: 12,
      100: 3,
    },
  },
  spend_by_category: {
    digital: { total_ghs: 12500, jobs: 8 },
    trade: { total_ghs: 3200, jobs: 3 },
    educator: { total_ghs: 960, jobs: 2 },
    online_income: { total_ghs: 550, jobs: 3 },
  },
  repeat_hire_rate: 0.38,
  total_spent_ghs: 17210,
  total_jobs_posted: 16,
  total_hires: 25,
  period_start: "2026-01-01T00:00:00Z",
  period_end: "2026-02-20T00:00:00Z",
};

// ── Income Certificate ──────────────────────

export const mockIncomeCertificates: IncomeCertificateMetadata[] = [
  {
    id: "ic001",
    worker_id: "w004",
    worker_name: "Yaw Takyi",
    total_lifetime_earnings_ghs: 12450,
    average_monthly_income_ghs: 691.67,
    months_active: 18,
    total_jobs_completed: 58,
    generated_at: "2026-02-15T10:00:00Z",
    certificate_number: "SKIL-INC-2026-000123",
    is_signed: true,
    signature_url: "https://cdn.cloudflare.r2.example.com/signatures/platform-signature.png",
    certificate_pdf_url: "https://cdn.cloudflare.r2.example.com/certificates/ic001.pdf",
    threshold_met: true,
    required_threshold_ghs: 5000,
  },
  {
    id: "ic002",
    worker_id: "w009",
    worker_name: "Kofi Asamoah",
    total_lifetime_earnings_ghs: 8200,
    average_monthly_income_ghs: 546.67,
    months_active: 15,
    total_jobs_completed: 67,
    generated_at: "2026-02-16T09:00:00Z",
    certificate_number: "SKIL-INC-2026-000124",
    is_signed: true,
    signature_url: "https://cdn.cloudflare.r2.example.com/signatures/platform-signature.png",
    certificate_pdf_url: "https://cdn.cloudflare.r2.example.com/certificates/ic002.pdf",
    threshold_met: true,
    required_threshold_ghs: 5000,
  },
  {
    id: "ic003",
    worker_id: "w001",
    worker_name: "Akua Serwaa",
    total_lifetime_earnings_ghs: 3800,
    average_monthly_income_ghs: 633.33,
    months_active: 6,
    total_jobs_completed: 34,
    generated_at: "2026-02-17T12:00:00Z",
    certificate_number: "SKIL-INC-2026-000125",
    is_signed: false,
    threshold_met: false,
    required_threshold_ghs: 5000,
  },
];
