// src/services/mocks/workers.ts
import type { Worker } from "@/types/worker";

export const mockWorkers: Worker[] = [
  {
    id: "w001",
    user_id: "u001",
    full_name: "Akua Serwaa",
    category: "digital",
    bio: "Frontend developer with 3 years building React and Next.js applications for Ghanaian startups.",
    location_district: "Accra Metropolitan",
    hourly_rate_ghs: 75.0,
    trust_score: 82.5,
    is_visible_in_search: true,
    verification_level: "verified",
    global_earner_status: false,
    badge: "Top Rated",
    completed_jobs: 34,
    skills: [
      { id: "s1", name: "React Developer", assessment_score: 88, verified: true, assessment_required: true },
      { id: "s2", name: "UI Designer", assessment_score: 75, verified: true, assessment_required: false },
      { id: "s3", name: "TypeScript", assessment_score: 90, verified: true, assessment_required: true },
    ],
    portfolio: [],
    reviews: [],
  },
  {
    id: "w002",
    user_id: "u002",
    full_name: "Kwame Boateng",
    category: "trade",
    bio: "Certified electrician with 8 years experience. Licensed by Energy Commission Ghana.",
    location_district: "Kumasi Metropolitan",
    hourly_rate_ghs: 50.0,
    trust_score: 68.0,
    is_visible_in_search: true,
    verification_level: "partial",
    global_earner_status: false,
    badge: "Rising Talent",
    completed_jobs: 12,
    skills: [
      { id: "s4", name: "Residential Electrician", verified: true, assessment_required: false },
      { id: "s5", name: "Commercial Wiring", verified: false, assessment_required: true },
    ],
    portfolio: [],
    reviews: [],
  },
  {
    id: "w003",
    user_id: "u003",
    full_name: "Ama Nyarko",
    category: "digital",
    bio: "Copywriter and content strategist for Ghanaian and African brands.",
    location_district: "Tema Metropolitan",
    hourly_rate_ghs: 45.0,
    trust_score: 55.0,
    is_visible_in_search: true,
    verification_level: "partial",
    global_earner_status: false,
    badge: null,
    completed_jobs: 7,
    skills: [
      { id: "s7", name: "Copywriting", assessment_score: 72, verified: true, assessment_required: true },
    ],
    portfolio: [],
    reviews: [],
  },
  {
    id: "w004",
    user_id: "u004",
    full_name: "Yaw Takyi",
    category: "trade",
    bio: "Professional plumber serving Accra East. 15 years experience.",
    location_district: "Adenta Municipal",
    hourly_rate_ghs: 60.0,
    trust_score: 91.0,
    is_visible_in_search: true,
    verification_level: "verified",
    global_earner_status: false,
    badge: "Verified Expert",
    completed_jobs: 58,
    skills: [
      { id: "s9", name: "Plumbing", verified: true, assessment_required: false },
    ],
    portfolio: [],
    reviews: [],
  },
  {
    id: "w005",
    user_id: "u005",
    full_name: "Kojo Essel",
    category: "trade",
    bio: "Tailor and fashion designer. Custom suits, traditional wear, alterations.",
    location_district: "Accra Metropolitan",
    hourly_rate_ghs: 40.0,
    trust_score: 73.0,
    is_visible_in_search: true,
    verification_level: "verified",
    global_earner_status: false,
    badge: "Top Rated",
    completed_jobs: 27,
    skills: [
      { id: "s14", name: "Tailoring", verified: true, assessment_required: false },
    ],
    portfolio: [],
    reviews: [],
  },
  {
    id: "w006",
    user_id: "u006",
    full_name: "Fatima Ibrahim",
    category: "digital",
    bio: "Virtual assistant and data entry specialist. Detail-oriented and reliable.",
    location_district: "Tamale Metropolitan",
    hourly_rate_ghs: 30.0,
    trust_score: 47.0,
    is_visible_in_search: true,
    verification_level: "partial",
    global_earner_status: false,
    badge: null,
    completed_jobs: 3,
    skills: [
      { id: "s12", name: "Virtual Assistant", assessment_score: 65, verified: true, assessment_required: true },
    ],
    portfolio: [],
    reviews: [],
  },
  {
    id: "w007",
    user_id: "u007",
    full_name: "Nana Kofi Mensah",
    category: "educator",
    bio: "Certified mathematics tutor with 5 years experience teaching BECE and WASSCE students. Experienced in both one-on-one and group tutoring.",
    location_district: "Accra Metropolitan",
    hourly_rate_ghs: 40.0,
    trust_score: 95.0,
    is_visible_in_search: true,
    verification_level: "verified",
    global_earner_status: false,
    badge: "Verified Expert",
    completed_jobs: 42,
    skills: [
      { id: "s15", name: "Mathematics Tutor", verified: true, assessment_required: true },
      { id: "s16", name: "BECE Preparation", verified: true, assessment_required: false },
      { id: "s17", name: "WASSCE Preparation", verified: true, assessment_required: false },
    ],
    portfolio: [],
    reviews: [],
    educator_details: {
      subjects: ["Mathematics", "Further Mathematics"],
      levels: ["JHS", "SHS"],
      session_price_ghs: 80,
      session_duration_minutes: 60,
      teaching_experience_years: 5,
      certifications: ["GES Certified Teacher", "KNUST BSc. Mathematics"],
      is_group_tutoring_available: true,
      max_group_size: 8,
    },
  },
  {
    id: "w008",
    user_id: "u008",
    full_name: "Efua Asantewaa",
    category: "educator",
    bio: "English language and literature tutor specializing in essay writing, grammar, and oral English. Helps students improve their communication skills.",
    location_district: "Kumasi Metropolitan",
    hourly_rate_ghs: 35.0,
    trust_score: 88.0,
    is_visible_in_search: true,
    verification_level: "verified",
    global_earner_status: false,
    badge: "Top Rated",
    completed_jobs: 29,
    skills: [
      { id: "s18", name: "English Tutor", verified: true, assessment_required: true },
      { id: "s19", name: "Essay Writing", verified: true, assessment_required: false },
    ],
    portfolio: [],
    reviews: [],
    educator_details: {
      subjects: ["English Language", "English Literature"],
      levels: ["Primary", "JHS", "SHS"],
      session_price_ghs: 70,
      session_duration_minutes: 45,
      teaching_experience_years: 4,
      certifications: ["GES Certified Teacher"],
      is_group_tutoring_available: true,
      max_group_size: 6,
    },
  },
  {
    id: "w009",
    user_id: "u009",
    full_name: "Kofi Asamoah",
    category: "online_income",
    bio: "Verified data entry and transcription specialist. Fast and accurate. 3 years experience working with international clients.",
    location_district: "Tema Metropolitan",
    hourly_rate_ghs: 25.0,
    trust_score: 92.0,
    is_visible_in_search: true,
    verification_level: "verified",
    global_earner_status: true,
    badge: "Top Rated",
    completed_jobs: 67,
    skills: [
      { id: "s20", name: "Data Entry", verified: true, assessment_required: true },
      { id: "s21", name: "Transcription", verified: true, assessment_required: true },
      { id: "s22", name: "Microsoft Excel", verified: true, assessment_required: false },
    ],
    portfolio: [],
    reviews: [],
    online_income_details: {
      preferred_task_types: ["Data Entry", "Transcription", "Excel Spreadsheets"],
      available_hours_per_week: 40,
      verified_data_entry: true,
      verified_transcription: true,
    },
  },
  {
    id: "w010",
    user_id: "u010",
    full_name: "Adwoa Boahene",
    category: "online_income",
    bio: "Micro‑tasks and survey specialist. Available 24/7 with fast turnaround time.",
    location_district: "Cape Coast Metropolitan",
    hourly_rate_ghs: 20.0,
    trust_score: 79.0,
    is_visible_in_search: true,
    verification_level: "partial",
    global_earner_status: false,
    badge: "Rising Talent",
    completed_jobs: 15,
    skills: [
      { id: "s23", name: "Data Entry", verified: false, assessment_required: true },
    ],
    portfolio: [],
    reviews: [],
    online_income_details: {
      preferred_task_types: ["Data Entry", "Surveys", "Micro‑Tasks"],
      available_hours_per_week: 30,
      verified_data_entry: false,
      verified_transcription: false,
    },
  },
];
