// src/services/mocks/workers.ts
import type { Worker } from "@/types/worker";

export const mockWorkers: Worker[] = [
  {
    id: "w001",
    user_id: "u001",
    full_name: "Akua Serwaa",
    category: "digital",
    bio: "Frontend developer with 3 years building React and Next.js applications for Ghanaian startups.",
    location_district: "Accra Metropolitan",
    hourly_rate_ghs: 75.0,
    trust_score: 82.5,
    is_visible_in_search: true,
    verification_level: "verified",
    global_earner_status: false,
    badge: "Top Rated",
    completed_jobs: 34,
    skills: [
      { id: "s1", name: "React Developer", assessment_score: 88, verified: true, assessment_required: true },
      { id: "s2", name: "UI Designer", assessment_score: 75, verified: true, assessment_required: false },
      { id: "s3", name: "TypeScript", assessment_score: 90, verified: true, assessment_required: true },
    ],
    portfolio: [],
    reviews: [],
  },
  {
    id: "w002",
    user_id: "u002",
    full_name: "Kwame Boateng",
    category: "trade",
    bio: "Certified electrician with 8 years experience. Licensed by Energy Commission Ghana.",
    location_district: "Kumasi Metropolitan",
    hourly_rate_ghs: 50.0,
    trust_score: 68.0,
    is_visible_in_search: true,
    verification_level: "partial",
    global_earner_status: false,
    badge: "Rising Talent",
    completed_jobs: 12,
    skills: [
      { id: "s4", name: "Residential Electrician", verified: true, assessment_required: false },
      { id: "s5", name: "Commercial Wiring", verified: false, assessment_required: true },
    ],
    portfolio: [],
    reviews: [],
  },
  {
    id: "w003",
    user_id: "u003",
    full_name: "Ama Nyarko",
    category: "digital",
    bio: "Copywriter and content strategist for Ghanaian and African brands.",
    location_district: "Tema Metropolitan",
    hourly_rate_ghs: 45.0,
    trust_score: 55.0,
    is_visible_in_search: true,
    verification_level: "partial",
    global_earner_status: false,
    badge: null,
    completed_jobs: 7,
    skills: [
      { id: "s7", name: "Copywriting", assessment_score: 72, verified: true, assessment_required: true },
    ],
    portfolio: [],
    reviews: [],
  },
  {
    id: "w004",
    user_id: "u004",
    full_name: "Yaw Takyi",
    category: "trade",
    bio: "Professional plumber serving Accra East. 15 years experience.",
    location_district: "Adenta Municipal",
    hourly_rate_ghs: 60.0,
    trust_score: 91.0,
    is_visible_in_search: true,
    verification_level: "verified",
    global_earner_status: false,
    badge: "Verified Expert",
    completed_jobs: 58,
    skills: [
      { id: "s9", name: "Plumbing", verified: true, assessment_required: false },
    ],
    portfolio: [],
    reviews: [],
  },
  {
    id: "w005",
    user_id: "u005",
    full_name: "Kojo Essel",
    category: "trade",
    bio: "Tailor and fashion designer. Custom suits, traditional wear, alterations.",
    location_district: "Accra Metropolitan",
    hourly_rate_ghs: 40.0,
    trust_score: 73.0,
    is_visible_in_search: true,
    verification_level: "verified",
    global_earner_status: false,
    badge: "Top Rated",
    completed_jobs: 27,
    skills: [
      { id: "s14", name: "Tailoring", verified: true, assessment_required: false },
    ],
    portfolio: [],
    reviews: [],
  },
  {
    id: "w006",
    user_id: "u006",
    full_name: "Fatima Ibrahim",
    category: "digital",
    bio: "Virtual assistant and data entry specialist. Detail-oriented and reliable.",
    location_district: "Tamale Metropolitan",
    hourly_rate_ghs: 30.0,
    trust_score: 47.0,
    is_visible_in_search: true,
    verification_level: "partial",
    global_earner_status: false,
    badge: null,
    completed_jobs: 3,
    skills: [
      { id: "s12", name: "Virtual Assistant", assessment_score: 65, verified: true, assessment_required: true },
    ],
    portfolio: [],
    reviews: [],
  },
];