// src/lib/mock-jobs.ts
import type { Job } from "@/types/job";

export const mockJobs: Job[] = [
  {
    id: "j001",
    employer_id: "e001",
    employer_name: "FinTech Ghana Ltd",
    employer_rating: 4.5,
    title: "React Frontend Developer for Mobile Banking Dashboard",
    description: "We need an experienced React developer to build a mobile-first dashboard for our banking app. The dashboard will display account balances, transaction history, fund transfer UI, and bill payment integration. Must be proficient in React, TypeScript, and responsive design. Experience with fintech or financial applications is a plus.",
    budget_ghs: 3000,
    status: "open",
    skills_required: ["React Developer", "TypeScript", "UI Designer"],
    posted_at: "2026-02-15T10:00:00Z",
    applications_count: 8,
    location_district: "Accra Metropolitan",
    is_remote: true,
  },
  {
    id: "j002",
    employer_id: "e002",
    employer_name: "Sarah's Event Planning",
    employer_rating: 4.0,
    title: "Custom Bridesmaid Dresses (6 pieces)",
    description: "Need a skilled tailor to create 6 bridesmaid dresses for a wedding in April. Fabric provided. Must be able to work with satin and lace. Measurements will be provided for all 6 women. Deadline is strict — must be completed by April 10th.",
    budget_ghs: 2400,
    status: "open",
    skills_required: ["Tailoring", "Fashion Design"],
    posted_at: "2026-02-14T08:30:00Z",
    applications_count: 3,
    location_district: "Accra Metropolitan",
    is_remote: false,
  },
  {
    id: "j003",
    employer_id: "e003",
    employer_name: "TechHub Accra",
    employer_rating: 4.8,
    title: "UI/UX Designer for SaaS Platform Redesign",
    description: "Looking for a talented UI/UX designer to redesign our SaaS platform. Must have experience with Figma, design systems, and user research. The project involves redesigning 12 core screens including dashboard, analytics, user management, and settings. Deliverables include wireframes, high-fidelity mockups, and a component design system.",
    budget_ghs: 5000,
    status: "open",
    skills_required: ["UI Designer", "Figma"],
    posted_at: "2026-02-13T14:00:00Z",
    applications_count: 15,
    location_district: "Accra Metropolitan",
    is_remote: true,
  },
  {
    id: "j004",
    employer_id: "e004",
    employer_name: "Kumasi Homes Ltd",
    employer_rating: 3.8,
    title: "Emergency Plumbing - Burst Pipe Repair",
    description: "Burst pipe in our newly built apartment block in Asokwa. Need an experienced plumber immediately. Must have own tools and be available within 2 hours. This is urgent — water is flooding the ground floor.",
    budget_ghs: 800,
    status: "open",
    skills_required: ["Plumbing", "Pipe Fitting"],
    posted_at: "2026-02-16T07:00:00Z",
    applications_count: 2,
    location_district: "Kumasi Metropolitan",
    is_remote: false,
  },
  {
    id: "j005",
    employer_id: "e005",
    employer_name: "Green Energy Solutions",
    employer_rating: 4.2,
    title: "Solar Panel Installation Technician",
    description: "Need a certified solar installation technician for a residential project in Tema. 12-panel system with battery backup. Must be Energy Commission certified and have at least 2 years of solar installation experience.",
    budget_ghs: 2000,
    status: "open",
    skills_required: ["Solar Installation", "Residential Electrician"],
    posted_at: "2026-02-12T11:00:00Z",
    applications_count: 5,
    location_district: "Tema Metropolitan",
    is_remote: false,
  },
  {
    id: "j006",
    employer_id: "e001",
    employer_name: "FinTech Ghana Ltd",
    employer_rating: 4.5,
    title: "Copywriter for Mobile App Launch Campaign",
    description: "We're launching a new mobile banking feature and need compelling copy for in-app notifications, email campaigns, social media posts, and a landing page. Experience with fintech copywriting preferred. Must be able to write in both English and Twi.",
    budget_ghs: 1500,
    status: "open",
    skills_required: ["Copywriting", "Content Strategy"],
    posted_at: "2026-02-11T09:00:00Z",
    applications_count: 12,
    location_district: "Accra Metropolitan",
    is_remote: true,
  },
  {
    id: "j007",
    employer_id: "e006",
    employer_name: "Adenta Auto Services",
    employer_rating: 3.5,
    title: "Auto Mechanic - Engine Overhaul",
    description: "Need an experienced auto mechanic for a complete engine overhaul on a Toyota Corolla 2018. Must have diagnostic tools and workshop space. Expected completion within 5 working days.",
    budget_ghs: 1500,
    status: "open",
    skills_required: ["Auto Mechanic"],
    posted_at: "2026-02-10T15:00:00Z",
    applications_count: 4,
    location_district: "Adenta Municipal",
    is_remote: false,
  },
  {
    id: "j008",
    employer_id: "e007",
    employer_name: "Digital Marketing Pro",
    employer_rating: 4.7,
    title: "Graphic Designer for Social Media Campaign",
    description: "Looking for a creative graphic designer to create 20 social media graphics for an upcoming product launch. Must be proficient in Adobe Creative Suite or Figma. Brand guidelines will be provided.",
    budget_ghs: 1000,
    status: "open",
    skills_required: ["Graphic Design"],
    posted_at: "2026-02-09T12:00:00Z",
    applications_count: 20,
    location_district: "Accra Metropolitan",
    is_remote: true,
  },
];



import type { PendingApplication } from "@/types/employer";

export interface MockJobDetail extends Job {
  applications: PendingApplication[];
  hired_worker?: string;
}

export const mockJobDetail: MockJobDetail = {
  id: "j001",
  employer_id: "e001",
  employer_name: "FinTech Ghana Ltd",
  employer_rating: 4.5,
  title: "React Frontend Developer for Mobile Banking Dashboard",
  description: "We need an experienced React developer to build a mobile-first dashboard for our banking app. The dashboard will display account balances, transaction history, fund transfer UI, and bill payment integration. Must be proficient in React, TypeScript, and responsive design. Experience with fintech or financial applications is a plus.\n\nDeliverables:\n- Interactive dashboard with real-time data updates\n- Transaction history with filtering\n- Fund transfer flow with confirmation screens\n- Bill payment integration\n- Responsive design for mobile and tablet",
  budget_ghs: 3000,
  status: "open",
  skills_required: ["React Developer", "TypeScript", "UI Designer"],
  posted_at: "2026-02-15T10:00:00Z",
  applications_count: 8,
  location_district: "Accra Metropolitan",
  is_remote: true,
  applications: [
    {
      id: "app001",
      job_id: "j001",
      job_title: "React Frontend Developer",
      worker_id: "w001",
      worker_name: "Akua Serwaa",
      worker_trust_score: 82.5,
      cover_note: "I have 3 years of React experience building fintech dashboards. My portfolio includes similar mobile banking projects for Ghanaian startups.",
      applied_at: "2026-02-16T08:00:00Z",
    },
    {
      id: "app002",
      job_id: "j001",
      job_title: "React Frontend Developer",
      worker_id: "w003",
      worker_name: "Ama Nyarko",
      worker_trust_score: 55.0,
      cover_note: "I am a fast learner with React and TypeScript. I have completed 7 projects on the platform with 5-star reviews.",
      applied_at: "2026-02-16T09:30:00Z",
    },
    {
      id: "app005",
      job_id: "j001",
      job_title: "React Frontend Developer",
      worker_id: "w005",
      worker_name: "Kojo Essel",
      worker_trust_score: 73.0,
      cover_note: "Full-stack developer with 5 years experience. Built 3 fintech applications. Available immediately.",
      applied_at: "2026-02-16T11:00:00Z",
    },
  ],
};